
author:
    - name: Jonathan De La Pena
      email: delapenajd@vcu.edu

date: last-modified

format:
    html:
        theme: morph
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
